CREATE TABLE vc_telco_api_doc.ObjectParameter
(
    ObjectParameterID int(11) NOT NULL AUTO_INCREMENT,
    ObjectParameterName varchar(64),
    ParameterType tinyint(4),
    ParameterObject int(11) DEFAULT '0',
    SubObject int(11),
    MaxVersion double,
    ObjectParameterOrder int(11) DEFAULT '10',
    Required tinyint(1) DEFAULT '0',
    Description varchar(1024) DEFAULT '',
    Example varchar(1024) DEFAULT '',
    MinVersion double,
    ParameterPermissionType int(11) DEFAULT '0'
);
CREATE UNIQUE INDEX ObjectParameter_ObjectParameterID_pk ON vc_telco_api_doc.ObjectParameter (ObjectParameterID);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderID', 2, 1, null, 1000, 10, 1, 'ProviderID', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderName', 1, 1, null, 1000, 10, 1, 'Provider Name', 'Voicenter1NY', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderStatus', 2, 1, null, 1000, 10, 1, '1 Enabled, 2 Disabled', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderCreateDate', 3, 1, null, 1000, 10, 1, 'When did this provider joined this server', '', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderAccount', 2, 1, null, 1000, 10, 1, 'Account ', '111', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderTenant', 1, 1, null, 1000, 10, 1, 'Tenant tag', 'voicenter', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixID', 2, 2, null, 1000, 10, 1, 'Prefix ID', '1111', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixNum', 1, 2, null, 1000, 10, 1, 'Digits of the prefix', '9725', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixName', 1, 2, null, 1000, 10, 1, 'Prefix Name', 'Israel Mobile', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixCountry', 2, 2, null, 1000, 10, 1, 'Country ID of the prefix', '19', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixType', 2, 2, null, 1000, 10, 1, 'Type of Prefix', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderPrefixRateLogID', 2, 9, null, 1000, 10, 1, 'Provider Prefix Rate Log ID', '123', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderPrefixLogSynchStatus', 2, 9, null, 1000, 10, 1, '1 Enabled, 2 Disabled', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixID', 2, 9, null, 1000, 10, 1, 'Prefix ID', '23034', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderPrefixRate', 13, 9, null, 1000, 10, 1, 'The object of the rate for this prefix', '{}', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixNum', 1, 3, null, 1000, 10, 1, 'prefix digits', '9725', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('StartDate', 3, 3, null, 1000, 10, 0, 'Starting date for the new rate to take affect', '2019-01-01', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Cost', 21, 3, null, 1000, 10, 1, 'The rates for this prefix in this provider', '0.01', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Data', 13, 3, null, 1000, 10, 0, 'JSON with more data regarding the prefix', '{PrefixName:"Israel Mobile"}', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderPrefixUpdateID', 2, 4, null, 1000, 10, 0, 'ID', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderPrefixUpdateDate', 3, 4, null, 1000, 10, 1, 'Date of last update', '', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderPrefixUpdateData', 13, 4, null, 1000, 10, 0, 'ProviderPrefixUpdateData - a json with more details on the update', '{}', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Currency', 2, 4, null, 1000, 10, 0, 'Currncy ID', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('CurrencyRate', 21, 4, null, 1000, 10, 0, '3.666', '', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountDataID', 2, 5, null, 1000, 10, 1, 'Primary key of account data', '', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountID', 2, 5, null, 1000, 10, 1, 'Account ID', '233', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Region', 2, 5, null, 1000, 10, 0, 'Region ID', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Country', 2, 5, null, 1000, 10, 0, 'Country ID', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixType', 2, 5, null, 1000, 10, 0, 'Prefix Type', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountDialRules', 13, 5, null, 1000, 10, 1, 'AccountDataJson', '{}', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('LoadStatus', 2, 5, null, 1000, 10, 1, 'LoadStatus', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderGatewayID', 2, 5, null, 1000, 10, 1, 'ID of gateway', '173', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('IP', 1, 6, null, 1000, 10, 0, 'IP address of the sip provider SIP server', '8.8.8.8', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderGatewayName', 1, 6, null, 1000, 10, 0, 'SIP Provider name', 'IDT', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Port', 1, 6, null, 1000, 10, 0, 'the port used for SIP', '5060', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('DtmfMode', 1, 6, null, 1000, 10, 0, 'DtmfMode', 'rfc2833', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderPrefix', 1, 6, null, 1000, 10, 0, 'ProviderPrefix', '99901', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Qualify', 1, 6, null, 1000, 10, 0, 'Qualify', 'yes', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Nat', 1, 6, null, 1000, 10, 0, 'Choose "force_rport,comedia" unless you KNOW something else is required.', 'force_rport,comedia', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Behaviour', 2, 6, null, 1000, 10, 0, 'Local / international', '2', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ParentProvider', 1, 6, null, 1000, 10, 0, 'Provider to be used for billing purposes', '0', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderGatewayStatus', 2, 6, null, 1000, 10, 1, '1 Enabled, 2 Disabled', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderGatewayCreatedate', 3, 6, null, 1000, 10, 1, 'Date of creation', '2019-01-01', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderGatewayIsshow', 2, 6, null, 1000, 10, 1, 'to show the provider in GUI?', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountDialRulesID', 2, 7, null, 1000, 10, 1, 'Primary Key ID for account dial rules', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountDialRulesCallerID', 1, 7, null, 1000, 10, 1, 'Caller id for this rule', '12127777777', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountProviderList', 14, 7, 1, 1000, 10, 1, '{}', '', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderGroupID', 2, 8, null, 1000, 10, 1, 'Primary Key ID for Provider Groups', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderGroupName', 1, 8, null, 1000, 10, 0, 'Providers group name', 'account836PGroup', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Provider', 2, 8, null, 1000, 10, 0, 'A provider in this group', '173', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Account', 2, 8, null, 1000, 10, 0, 'The account the group is assigned to', '836', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ID', 2, 9, null, 1000, 10, 0, 'ID of ProviderPrefix', '664533', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderID', 2, 9, null, 1000, 10, 0, 'Provider ID in provider prefix', '173', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixNum', 1, 9, null, 1000, 10, 0, 'Prefix digits', '9725', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Region', 2, 9, null, 1000, 10, 0, 'The ID of the region', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Country', 2, 9, null, 1000, 10, 0, 'The ID of the Country', '19', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixType', 2, 9, null, 1000, 10, 0, 'The type of prefix (Landline/Mobile/Premium/TollFree...)', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixID', 2, 9, null, 1000, 10, 0, 'Prefix ID in Provider prefix', '22304', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Cost', 21, 9, null, 1000, 10, 0, 'The cost per minute for this provider', '0.01', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ID', 2, 10, null, 1000, 10, 0, 'Primary Key ID of account providers', '1', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountDataID', 2, 10, null, 1000, 10, 0, 'account data id', '{}', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderID', 2, 10, null, 1000, 10, 0, 'Provider ID', '173', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('weight', 2, 10, null, 1000, 10, 0, 'Weight for this account provider settings', '10', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Code', 2, 11, null, 1000, 10, 1, 'Code of the Error', '200', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Description', 1, 11, null, 1000, 10, 1, 'Textual description of the error', 'OK', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ReasonPhrase', 1, 11, null, 1000, 10, 0, 'Specific reason for the error', '', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Code', 2, 12, null, 1000, 10, 1, 'Code of error', '500', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Description', 1, 12, null, 1000, 10, 1, 'Description of error', 'Provider not found', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ReasonPhrase', 1, 12, null, 1000, 10, 1, 'Specific reason for the error', 'No provider with such ID exsist in the system', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProvidersListInfo', 14, 14, 1, 1000, 10, 1, 'Array of Providers', '[{"Provider Name":"Voicenter2NY","ProviderStatus":1,"ProviderTenant":"voicenterTenant1",ProviderAccount":111,"ProviderCreateDate":($date-time)}]', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProvidersAddList', 14, 15, 16, 1000, 10, 1, 'Array of Providers without ID, for adding single/bulk providers.', '[{"Provider Name":"Voicenter2NY","ProviderStatus":1,"ProviderTenant":"voicenterTenant1",ProviderAccount":111,"ProviderCreateDate":($date-time)}]', 0, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderName', 1, 16, null, 1000, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderStatus', 2, 16, null, 1000, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderCreateDate', 3, 16, null, 1000, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderAccount', 2, 16, null, 1000, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderTenant', 1, 16, null, 1000, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProvidersDisableList', 14, 17, 18, 1000, 10, 1, 'ID of Provider/s to disable', '173', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderID', 2, 18, null, 1000, 10, 1, 'ID to disable', '173', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderPrefixAddList', 14, 19, 20, 1000, 10, 0, 'List of provider prefix data (provider rates per prefix) to insert', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderID', 2, 20, null, 1000, 10, 1, 'Provider ID in provider prefix', '173', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixNum', 1, 20, null, 1000, 10, 1, 'Prefix digits', '9725', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Region', 2, 20, null, 1000, 10, 0, 'The ID of the region', '1', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Country', 2, 20, null, 1000, 10, 0, 'The ID of the Country', '19', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixType', 2, 20, null, 1000, 10, 0, 'The type of prefix (Landline/Mobile/Premium/TollFree...)', '1', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixID', 2, 20, null, 1000, 10, 0, 'Prefix ID in Provider prefix', '22304', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Cost', 21, 20, null, 1000, 10, 0, 'The cost per minute for this provider', '0.01', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderPrefixUpdateList', 14, 21, 9, 1000, 10, 0, 'Provider Prefix array to be updated', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderPrefixList', 14, 23, 2, null, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Description', 1, 23, null, null, 10, 0, '', 'OK', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Code', 2, 23, null, null, 10, 0, '', '200', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderPrefixUpdateID', 2, 24, null, null, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Description', 1, 24, null, null, 10, 0, '', 'OK', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Code', 2, 24, null, null, 10, 0, '', '200', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Description', 1, 25, null, null, 10, 0, '', 'OK', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Code', 2, 25, null, null, 10, 0, '', '200', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderPrefixUpdateID', 2, 26, null, null, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('RatesList', 14, 26, 3, null, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountName', 1, 27, null, null, 10, 0, '', 'MyBestAccount-CompanyName', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Tanent', 1, 27, null, null, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountStatus', 2, 27, null, null, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountID', 2, 27, null, null, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountParent', 2, 27, null, null, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountNameList', 6, 28, null, null, 10, 0, '', 'MyBestAccount-CompanyName', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('TanentList', 6, 28, null, null, 10, 0, '', 'tenantName', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountStatusList', 27, 28, null, null, 10, 0, '', '1', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountIDList', 27, 28, null, null, 10, 0, '', '1', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('AccountParentList', 27, 28, null, null, 10, 0, '', '101', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixListResponseCode', 2, 30, null, null, 10, 0, '', '200', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('PrefixListResponseList', 14, 30, 2, null, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ServerProviderGatewayID', 2, 31, null, null, 10, 0, ' ', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ServerID', 2, 31, null, null, 10, 0, ' ', ' ', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('ProviderGatewayID', 2, 31, null, null, 10, 0, '', '', null, 0);
INSERT INTO vc_telco_api_doc.ObjectParameter (ObjectParameterName, ParameterType, ParameterObject, SubObject, MaxVersion, ObjectParameterOrder, Required, Description, Example, MinVersion, ParameterPermissionType) VALUES ('Status', 2, 31, null, null, 10, 0, '', '', null, 0);