CREATE TABLE MethodParameter
(
    MethodParameterID int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    MethodID int(11) DEFAULT '0' NOT NULL,
    MethodParameterPlace tinyint(4) DEFAULT '1',
    MethodParameterName varchar(64),
    ParameterType tinyint(4),
    ParameterObject int(11) DEFAULT '0',
    MinVersion double DEFAULT '0',
    MaxVersion double DEFAULT '1000',
    MethodParameterOrder int(11) DEFAULT '10',
    Required tinyint(1) DEFAULT '0' NOT NULL,
    Description varchar(1024) DEFAULT '' NOT NULL,
    Example varchar(1024),
    ParameterPermissionType int(11) DEFAULT '0'
);
CREATE UNIQUE INDEX MethodParameterPlaceName_pk ON MethodParameter (MethodID, MethodParameterPlace, MethodParameterName);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (1, 4, 'ProvidersAddInfo', 13, 1, 0, 1000, 10, 1, 'Adding new provider', '[{"Provider Name":"Voicenter2NY","ProviderStatus":1,"ProviderTenant":"voicenterTenant1",ProviderAccount":111,"ProviderCreateDate":($date-time)}]', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (2, 5, 'ProviderList', 13, 14, 0, 1000, 10, 0, '', '[{"Provider Name":"Voicenter2NY","ProviderStatus":1,"ProviderTenant":"voicenterTenant1",ProviderAccount":111,"ProviderCreateDate":($date-time)}]', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (2, 3, 'Status', 1, 0, 0, 1000, 10, 0, '', '0', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (3, 4, 'ProvidersEditInfo', 13, 1, 0, 1000, 10, 1, 'Updating provider/s', '[{"Provider Name":"Voicenter2NY","ProviderStatus":1,"ProviderTenant":"voicenterTenant1",ProviderAccount":111,"ProviderCreateDate":($date-time)}]', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (4, 1, 'ProviderID', 2, 0, 0, 1000, 10, 1, 'Delete Provider/s by ID', '11', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (5, 1, 'ProviderID', 13, 0, 0, 1000, 10, 1, 'ProviderPrefix Adding', '', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (5, 5, 'ProviderPrefixListResponse', 13, 23, 0, 1000, 10, 0, '', '', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (8, 4, 'ProviderPrefixUpdate', 13, 22, 0, 1000, 10, 0, '', '', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (8, 5, 'ProviderPrefixUpdateResponse', 13, 24, 0, 1000, 10, 0, '', '', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (9, 4, 'ProviderPrefixBulkRequest', 13, 26, 0, 1000, 10, 0, '', '6', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (9, 5, 'ProviderPrefixBulkResponse', 13, 25, 0, 1000, 10, 0, '', '', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (4, 2, 'ProviderStatus', 2, 0, 0, 1000, 10, 1, 'status of provider ', '11', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (10, 4, 'AccountInfo', 13, 27, 0, 1000, 10, 1, 'Adding new Account', '[{"Provider Name":"Voicenter2NY","ProviderStatus":1,"ProviderTenant":"voicenterTenant1",ProviderAccount":111,"ProviderCreateDate":($date-time)}]', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (11, 4, 'AccountList', 13, 28, 0, 1000, 10, 1, 'Searching for Account that meets the query. multiple values are support. multiple selections in same feild will be treated as OR, multiple feilds will be searched with OR between them.', '{', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (12, 4, 'AccountUpdate', 13, 27, 0, 1000, 10, 0, 'Account update', '', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (13, 1, 'AccountStatusUpdate', 2, 0, 0, 1000, 10, 0, 'Account disabling', '', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (14, 1, 'PrefixListRequest', 2, 0, 0, 1000, 10, 0, 'Request info of prefix', '', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (14, 4, 'PrefixListResponse', 13, 30, 0, 1000, 10, 0, 'Prefix List Response', '', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (15, 4, 'ProviderGatewayAdd', 13, 6, 0, 1000, 10, 0, 'Add Provider Gateway', '', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (16, 4, 'ProviderGatewayUpdate', 13, 6, 0, 1000, 10, 0, 'Update Provider Gateway', '', 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (17, 1, 'ProviderGatewayList', 2, 0, 0, 1000, 10, 0, 'list gws', null, 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (18, 1, 'ProviderGatewayStatusUpdate', 2, 0, 0, 1000, 10, 0, 'Disables gw', null, 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (19, 4, 'AccountProvidersAdd', 13, 10, 0, 1000, 10, 0, 'Account Providers Add', null, 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (20, 4, 'AccountProvidersList', 13, 10, 0, 1000, 10, 0, 'Account Providers List', null, 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (21, 4, 'AccountProvidersUpdate', 13, 10, 0, 1000, 10, 0, 'Account Providers Update', null, 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (22, 1, 'AccountProvidersStatusUpdate', 2, 0, 0, 1000, 10, 0, 'Disable Providers Status Update', null, 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (23, 4, 'ServerProviderGatewaysAdd', 13, 31, 0, 1000, 10, 0, '', null, 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (24, 4, 'ServerProviderGatewaysList', 14, 31, 0, 1000, 10, 0, '', null, 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (25, 4, 'ServerProviderGatewaysUpdate', 14, 31, 0, 1000, 10, 0, '', null, 0);
INSERT INTO MethodParameter (MethodID, MethodParameterPlace, MethodParameterName, ParameterType, ParameterObject, MinVersion, MaxVersion, MethodParameterOrder, Required, Description, Example, ParameterPermissionType) VALUES (26, 1, 'ServerProviderGatewayUpSt', 2, 0, 0, 1000, 10, 0, '', null, 0);